
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class showClass extends javax.swing.JFrame {

    /**
     * Creates new form showClass
     */
    PreparedStatement pstmt;
    Statement stmt;
    public showClass() {
        initComponents();
        displayTable();
        load_dept();
    }
    
    public void table_update(){
        try{
        Connection con = consetup.createCon();
        String q="select * from class";
        Statement st= con.createStatement();
        ResultSet set=st.executeQuery(q);
        DefaultTableModel m=(DefaultTableModel) tblshowclass.getModel();
        m.setRowCount(0);
        while(set.next())
        {
            
            String c_id=set.getString(1);
            String class_name=set.getString(2);
            
            m.insertRow(tblshowclass.getRowCount(), new Object[]{
            c_id,
                class_name
            });
        }
        
        }
        catch(Exception e)
        {
        e.printStackTrace();
        }
    }
    
    
    public void load_dept(){
        try
        {
        Connection con=consetup.createCon();
        
        String q="select * from department;";
        Statement st = con.createStatement();
        ResultSet re = st.executeQuery(q);
        cmbDept.removeAllItems();
        while(re.next())
        {
            cmbDept.addItem(re.getString("dept_name"));
        }
        
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    
    
    public void displayTable()
    {
        try{
        Connection con= consetup.createCon();
        DefaultTableModel m = (DefaultTableModel)tblshowclass.getModel();
        
        String q="select * from class;";
        stmt= con.createStatement();
        ResultSet re = stmt.executeQuery(q);
        m.setRowCount(0);
        while(re.next())
            {
                String C_name=re.getString(1);
                String class_roomNumber=re.getString(2);
                
                m.insertRow(m.getRowCount(), new Object[] {
                C_name,
                class_roomNumber,
                re.getString(3)
                });
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblshowclass = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtclassName = new javax.swing.JTextField();
        txtRoomNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSaveClass = new javax.swing.JButton();
        btnEditClass = new javax.swing.JButton();
        btnDeleteClass = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbDept = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblshowclass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblshowclass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Class Name", "Room no", "dept"
            }
        ));
        tblshowclass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblshowclassMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblshowclass);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("class name");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("class room No");

        btnSaveClass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSaveClass.setText("save");
        btnSaveClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveClassActionPerformed(evt);
            }
        });

        btnEditClass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditClass.setText("edit");
        btnEditClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditClassActionPerformed(evt);
            }
        });

        btnDeleteClass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDeleteClass.setText("delete");
        btnDeleteClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteClassActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("department");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-classroom-64.png"))); // NOI18N
        jLabel4.setText("Class Registration");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtclassName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRoomNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDept, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEditClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteClass, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .addComponent(btnSaveClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtclassName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbDept, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addComponent(btnSaveClass, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditClass, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnDeleteClass, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblshowclassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblshowclassMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel m=(DefaultTableModel) tblshowclass.getModel();
        int selectedIndex = tblshowclass.getSelectedRow();
        txtclassName.setText(m.getValueAt(selectedIndex,0).toString());
        txtRoomNo.setText(m.getValueAt(selectedIndex,1).toString());
        cmbDept.setSelectedItem(m.getValueAt(selectedIndex,2).toString());
    }//GEN-LAST:event_tblshowclassMouseClicked

    private void btnSaveClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveClassActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        try{
        Connection con=consetup.createCon();
        String c_name;
        int c_roomNo;
        c_name=txtclassName.getText();
        c_roomNo= Integer.parseInt(txtRoomNo.getText());
        
        
        String q="insert into class(name,roomno,dept) values(?,?,?);";
	pstmt = con.prepareStatement(q);
        pstmt.setString(1,c_name);
	pstmt.setInt(2,c_roomNo);
        pstmt.setString(3,cmbDept.getSelectedItem().toString());
	

        
        pstmt.executeUpdate();
        JOptionPane.showMessageDialog(this, "success");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "error has occured");
        e.printStackTrace();
        }
        finally{
        txtclassName.setText("");
        txtRoomNo.setText("");
        
        displayTable();
        }
        
        
    }//GEN-LAST:event_btnSaveClassActionPerformed

    private void btnEditClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditClassActionPerformed
        // TODO add your handling code here:
        
//        you have to add a function that tells you that the class that you want to edit doesnt exist
        try {
            Connection con = consetup.createCon();
            String q="update class set name=?, dept=? where roomno=?";
            pstmt=con.prepareStatement(q);
            pstmt.setString(1, txtclassName.getText());
            pstmt.setString(2, cmbDept.getSelectedItem().toString());
            pstmt.setInt(3, Integer.parseInt(txtRoomNo.getText()));
            pstmt.executeUpdate();
            displayTable();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEditClassActionPerformed

    private void btnDeleteClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteClassActionPerformed
        // TODO add your handling code here:
        try{
        Connection con = consetup.createCon();
        String q="delete from class where roomno=?;";
        DefaultTableModel m= (DefaultTableModel) tblshowclass.getModel();
        int selectedIndex = tblshowclass.getSelectedRow();
        int room_no= Integer.parseInt(txtRoomNo.getText());
        pstmt =con.prepareStatement(q);
        pstmt.setInt(1, room_no);
        pstmt.executeUpdate();
        displayTable();
        JOptionPane.showMessageDialog(this, "record deleted");
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDeleteClassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteClass;
    private javax.swing.JButton btnEditClass;
    private javax.swing.JButton btnSaveClass;
    private javax.swing.JComboBox<String> cmbDept;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblshowclass;
    private javax.swing.JTextField txtRoomNo;
    private javax.swing.JTextField txtclassName;
    // End of variables declaration//GEN-END:variables
}
