
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class Showfaculty extends javax.swing.JFrame {

    /**
     * Creates new form Showfaculty
     */
    public Showfaculty() {
        initComponents();
        displayTablefaculty();
        load_dept();
    }
    Statement stmt;
    PreparedStatement pstmt;
    
    public void load_dept(){
        try
        {
        Connection con=consetup.createCon();
        
        String q="select * from department;";
        Statement st = con.createStatement();
        ResultSet re = st.executeQuery(q);
        cmbDept.removeAllItems();
        while(re.next())
        {
            cmbDept.addItem(re.getString("dept_name"));
        }
        
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    public void displayTablefaculty()
    {
        try{
        Connection con= consetup.createCon();
        DefaultTableModel m = (DefaultTableModel)tblFacultyShow.getModel();
        
        String q="select * from faculty;";
        stmt= con.createStatement();
        ResultSet re = stmt.executeQuery(q);
        m.setRowCount(0);
        while(re.next())
            {
                String id=re.getString(1);
                String f_name=re.getString(2);
                String f_phone=re.getString(3);
                String f_subject=re.getString(4);
                String f_education=re.getString(5);
                String f_rank=re.getString(6);
                String f_birth=re.getString(7);
                String f_address=re.getString(8);
                
                m.insertRow(m.getRowCount(), new Object[] {
                id,
                f_name,
                f_phone,
                f_subject,
                f_education,
                f_rank,
                f_birth,
                f_address      
                });
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFacultyShow = new javax.swing.JTable();
        txtFacultySubject = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtFacultyName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFacultyphone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtFacultyEducation = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFacultyRank = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBirth = new javax.swing.JTextField();
        cmbDept = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblFacultyShow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblFacultyShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fid", "Name", "Phonenumber", "Preferedsub", "Education", "Rank", "Birthdate", "Department"
            }
        ));
        tblFacultyShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFacultyShowMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFacultyShow);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("prefered subject");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("faculty name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("faculty phone");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("education");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("rank");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("birth date");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("department");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-people-50.png"))); // NOI18N
        jLabel7.setText("faculty registration");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFacultyName, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFacultyphone, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFacultySubject, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFacultyEducation, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFacultyRank, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDept, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFacultyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFacultyphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFacultySubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFacultyEducation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFacultyRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(37, 37, 37)
                        .addComponent(jButton1)
                        .addGap(44, 44, 44)
                        .addComponent(jButton2)
                        .addGap(38, 38, 38)
                        .addComponent(jButton3)))
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        Connection con=consetup.createCon();
        String f_name,f_address,f_birthdate;
        int f_id;
        f_name=txtFacultyName.getText();
        f_address=txtFacultyphone.getText();
        
        
//        f_id= Integer.parseInt(txtFacultyID.getText());
        
        
        String q="insert into faculty(fname,f_phonenumber,fpreferedsub,education,frank,birthdate,fdept) values(?,?,?,?,?,?,?);";
	pstmt = con.prepareStatement(q);
        pstmt.setString(1,f_name);
        pstmt.setString(2,txtFacultyphone.getText());
        pstmt.setString(3,txtFacultySubject.getText());
        pstmt.setString(4,txtFacultyEducation.getText());
        pstmt.setString(5,txtFacultyRank.getText());
        pstmt.setString(6,txtBirth.getText());
        
        pstmt.setString(7,cmbDept.getSelectedItem().toString());
        
        


        
        pstmt.executeUpdate();
        JOptionPane.showMessageDialog(this, "success");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "error has occured");
        e.printStackTrace();
        }
        finally{
        txtFacultySubject.setText("");
        txtFacultyphone.setText("");
        txtFacultyEducation.setText("");
        txtFacultyRank.setText("");
        txtBirth.setText("");
        txtFacultyName.setText("");
        
        displayTablefaculty();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblFacultyShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFacultyShowMouseClicked
        // TODO add your handling code here:
         DefaultTableModel m=(DefaultTableModel) tblFacultyShow.getModel();
        int selectedIndex = tblFacultyShow.getSelectedRow();
        txtFacultyName.setText(m.getValueAt(selectedIndex,1).toString());
        txtFacultyphone.setText(m.getValueAt(selectedIndex,2).toString());
        txtFacultySubject.setText(m.getValueAt(selectedIndex,3).toString());
        txtFacultyEducation.setText(m.getValueAt(selectedIndex,4).toString());
        txtFacultyRank.setText(m.getValueAt(selectedIndex,5).toString());
        txtBirth.setText(m.getValueAt(selectedIndex,6).toString());
        cmbDept.setSelectedItem(m.getValueAt(selectedIndex,7).toString());
        
    }//GEN-LAST:event_tblFacultyShowMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try {
            Connection con = consetup.createCon();
             DefaultTableModel m=(DefaultTableModel) tblFacultyShow.getModel();
             int selectedIndex = tblFacultyShow.getSelectedRow();
            int id= Integer.parseInt(m.getValueAt(selectedIndex,0).toString());
            
            String q="update faculty set fname=?,f_phonenumber=?,fpreferedsub=?,education=?,frank=?,birthdate=?,fdept=? where fid=?;";
            pstmt=con.prepareStatement(q);
            pstmt.setString(1, txtFacultyName.getText());
            pstmt.setString(2, txtFacultyphone.getText());
            pstmt.setString(3, txtFacultySubject.getText());
            pstmt.setString(4, txtFacultyEducation.getText());
            pstmt.setString(5, txtFacultyRank.getText());
            pstmt.setString(6, txtBirth.getText());
            pstmt.setString(7, cmbDept.getSelectedItem().toString());
            
            pstmt.setInt(8, id);
            pstmt.executeUpdate();
            
            txtFacultySubject.setText("");
            txtFacultyphone.setText("");
            txtFacultyEducation.setText("");
            txtFacultyRank.setText("");
            txtBirth.setText("");
            txtFacultyName.setText("");
            
            displayTablefaculty();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try{
        Connection con = consetup.createCon();
        String q="delete from faculty where fid=?;";
        DefaultTableModel m= (DefaultTableModel) tblFacultyShow.getModel();
        int selectedIndex = tblFacultyShow.getSelectedRow();
        int id= Integer.parseInt(m.getValueAt(selectedIndex,0).toString());
        pstmt =con.prepareStatement(q);
        pstmt.setInt(1, id);
        pstmt.executeUpdate();
        
        txtFacultySubject.setText("");
        txtFacultyphone.setText("");
        txtFacultyEducation.setText("");
        txtFacultyRank.setText("");
        txtBirth.setText("");
        txtFacultyName.setText("");
        
        displayTablefaculty();
        JOptionPane.showMessageDialog(this, "record deleted");
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Showfaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Showfaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Showfaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Showfaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Showfaculty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbDept;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFacultyShow;
    private javax.swing.JTextField txtBirth;
    private javax.swing.JTextField txtFacultyEducation;
    private javax.swing.JTextField txtFacultyName;
    private javax.swing.JTextField txtFacultyRank;
    private javax.swing.JTextField txtFacultySubject;
    private javax.swing.JTextField txtFacultyphone;
    // End of variables declaration//GEN-END:variables
}
